version: '2'

networks:
   ci-network:
    driver: bridge

services:
   sonarqube:
      container_name: sonarqube
      image: stratus-ci.eng.scalefocus.com:18442/sonarqube:5.6.1
#      ports:  //left for debugging
#         - "19000:9000"
      external_links:
         - sonardb:db
      networks:
         - ci-network
      depends_on:
         - sonardb
      mem_limit: 2048m
      logging:
         driver: json-file
         options:
            max-size: "50m"
            max-file: "4"
      environment:
         - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
         - SONARQUBE_JDBC_USERNAME=sonar
         - SONARQUBE_JDBC_PASSWORD=D07BADD0A69C41297850DCAD1B5CF7
      volumes_from:
         - plugins
      entrypoint: ./bin/run.sh -Dsonar.web.context=/sonar
      restart: always

   plugins:
      container_name: sonarqube-plugins
      networks:
          - ci-network
      image: stratus-ci.eng.scalefocus.com:18442/sonarqube:5.6.1
      volumes:
       - /opt/sonarqube/extensions
       - /opt/sonarqube/lib/bundled-plugins
      command: /bin/true

   install_plugins:
      container_name: sonarqube-install-plugins
      networks:
         - ci-network
      build: sonarqube/plugins
      volumes_from:
         - plugins

   sonardb:
      container_name: sonarqube-sonardb
      networks:
         - ci-network
      image: stratus-ci.eng.scalefocus.com:18442/postgres:9.5.5
      mem_limit: 512m
      logging:
         driver: json-file
         options:
            max-size: "50m"
            max-file: "4"
      environment:
         - POSTGRES_USER=sonar
         - POSTGRES_PASSWORD=D07BADD0A69C41297850DCAD1B5CF7
      volumes:
         - /var/opt/stratus-ci/sonardb/postgres/data:/var/lib/postgresql/data

   jenkins:
      build:
         context: ./jenkins
         dockerfile: Dockerfile
      container_name: jenkins
      mem_limit: 3536m
      environment:
         - JAVA_OPTS=-Dhudson.model.ParametersAction.safeParameters=SVC_NAME,TAG_ID,CLUSTER_NAME,TARGET_HOST -Dhudson.model.DirectoryBrowserSupport.CSP="default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
      entrypoint: /bin/tini -- /usr/local/bin/jenkins.sh --prefix=/jenkins --sessionTimeout=10080
      ports:
#      Port left for debugging
#         - "8000:8080"
         - "50000:50000"
      restart: always
      logging:
         driver: json-file
         options:
            max-size: "50m"
            max-file: "4"
      networks:
         - ci-network
      volumes:
         - /var/opt/stratus-ci/jenkins/jenkins_home:/var/jenkins_home

   docker-ui:
      image: stratus-ci.eng.scalefocus.com:18442/portainer/portainer
      container_name: docker-ui
      mem_limit: 64m
      logging:
         driver: json-file
         options:
            max-size: "50m"
            max-file: "4"
      ports:
         - "9000:9000"
      privileged: true
      restart: always
      networks:
         - ci-network
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - /usr/local/bin/docker:/usr/bin/docker

   nginx:
      build:
         context: ./nginx
         dockerfile: Dockerfile
      container_name: nginx
      mem_limit: 100m
      logging:
         driver: json-file
         options:
            max-size: "50m"
            max-file: "4"
      ports:
         - "80:80"
         - "443:443"
      networks:
         - ci-network
      restart: always
      volumes:
         - /var/opt/stratus-ci/nginx/log:/var/log/nginx/
         - /opt/stratus/certificates:/etc/nginx/certificates/
      links:
         - jenkins
         - docker-ui
         - gerrit
         - sonarqube
         - nexus

   gerrit-mariadb:
      build:
         context: ./gerrit-mariadb
         dockerfile: Dockerfile
      container_name: gerrit-mariadb
      mem_limit: 512m
      logging:
         driver: json-file
         options:
            max-size: "50m"
            max-file: "4"
      environment:
         - "MYSQL_ROOT_PASSWORD=81F5E21E35407D884A6CD4A731AEBFB6AF209E1B"
      ports:
         - "3306:3306"
      networks:
         - ci-network
      restart: always
      volumes:
         - /var/opt/stratus-ci/gerrit-mariadb/mysql/:/var/lib/mysql/

   gerrit:
      build:
         context: ./gerrit
         dockerfile: Dockerfile
      container_name: gerrit
      mem_limit: 1536m
      logging:
         driver: json-file
         options:
            max-size: "50m"
            max-file: "4"
      links:
         - gerrit-mariadb
         - jenkins
      ports:
#         - "8000:8080"
         - "29418:29418"
      networks:
         - ci-network
      restart: always
      volumes:
         - /var/opt/stratus-ci/gerrit/review_site/:/var/gerrit/review_site/

   nexus:
      build:
         context: ./nexus
         dockerfile: Dockerfile
      container_name: nexus
      mem_limit: 3512m
      logging:
         driver: json-file
         options:
            max-size: "50m"
            max-file: "4"
      ports:
#         - "8081:8081"
         - "18441:18441"
         - "18442:18442"
         - "18443:18443"
         - "18444:18444"
         - "18445:18445"
         - "18446:18446"
         - "18447:18447"
      networks:
         - ci-network
      dns: 10.124.10.5
      volumes:
         - /var/opt/stratus-ci/nexus/nexus-data:/nexus-data
         - /opt/stratus/certificates/:/opt/sonatype/nexus/etc/jetty/ssl:ro
      restart: always

   dhcpd:
      build:
         context: ./dhcpd
         dockerfile: Dockerfile
      container_name: dhcpd
      mem_limit: 64m
      logging:
         driver: json-file
         options:
            max-size: "50m"
            max-file: "4"
      network_mode: "host"
      restart: always
